version: '3.7'
services:
  database:
    image: postgres
    container_name: eatseazy-database
    environment:
      - POSTGRES_DB=eatseazy
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./database:/database
    ports:
      - 5432:5432

  backend:
    build:
      dockerfile: ./docker/Dockerfile
      context: ../
    image: 580496557684.dkr.ecr.eu-west-2.amazonaws.com/eatseazy/backend
    container_name: eatseazy-backend
    env_file:
      - ../.env
    ports:
      - 8080:80
    links:
      - database:database
    depends_on:
      - database
